# Generated by Django 4.0.6 on 2022-07-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.URLField()),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
