# Generated by Django 4.0.6 on 2022-08-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ('num_for_sort',), 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='clients',
            name='num_for_sort',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
