# Generated by Django 4.0.6 on 2022-08-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0003_project_description_en_project_description_kgz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description_kgz',
            new_name='description_ky',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title_kgz',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='title_kgz',
            new_name='title_ky',
        ),
    ]
